name: PillTracker 2
favicon: null
layout_spectrum: 0.35460367100313306
typography_spectrum: 0.6551254207734019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9264708049595356
  lightness: 0.39638045872561634
  saturation: 0.9423632519319654
  rhythmicContrast: 0.7209282726980746
purpose: []
