name: PillTracker 2
favicon: null
layout_spectrum: 0.33172
typography_spectrum: 0.43598
title: PillTracker LTD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#08b4c8'
    - '#8fc225'
    - '#89e1e6'
    - '#c9e591'
  brandStrength: 0.625
  lightness: 0.39638045872561634
  saturation: 0.9423632519319654
  rhythmicContrast: 0.7209282726980746
purpose: []
